# Generated by Django 4.1.3 on 2024-01-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='51f6fb256629fc755b8870c801092942.png', upload_to='profile'),
        ),
    ]
