# Generated by Django 4.1.3 on 2024-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_address_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
