# Generated by Django 4.1.3 on 2024-02-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_address_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'NOT PACKED'), (2, 'PACKED'), (3, 'Shipped'), (4, 'Delivered')], default='1', max_length=20),
        ),
    ]
