# Generated by Django 4.1.3 on 2024-02-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
